// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcwSZ4c4FnhxHSQPql0k_NV_jGeBo56g',
    appId: '1:252150989937:web:52b9159c8e08501b63c7d0',
    messagingSenderId: '252150989937',
    projectId: 'blood-donorapp-42c7a',
    authDomain: 'blood-donorapp-42c7a.firebaseapp.com',
    storageBucket: 'blood-donorapp-42c7a.appspot.com',
    measurementId: 'G-2ZQX58GF2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE73F3c74W2_IIc7hivBISeCafVVnZ8xk',
    appId: '1:252150989937:android:53116644571be66763c7d0',
    messagingSenderId: '252150989937',
    projectId: 'blood-donorapp-42c7a',
    storageBucket: 'blood-donorapp-42c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZoD-CSPPQu7H5a1ezcM-Cjx3NsbkmoYU',
    appId: '1:252150989937:ios:4f635426d4f1651263c7d0',
    messagingSenderId: '252150989937',
    projectId: 'blood-donorapp-42c7a',
    storageBucket: 'blood-donorapp-42c7a.appspot.com',
    iosBundleId: 'com.example.bloodDonorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZoD-CSPPQu7H5a1ezcM-Cjx3NsbkmoYU',
    appId: '1:252150989937:ios:a9d481baa4ac5aef63c7d0',
    messagingSenderId: '252150989937',
    projectId: 'blood-donorapp-42c7a',
    storageBucket: 'blood-donorapp-42c7a.appspot.com',
    iosBundleId: 'com.example.bloodDonorapp.RunnerTests',
  );
}
